pipeline:
  name: p3
  identifier: p3
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  delegateSelectors:
    - eks
    - prod
  stages:
    - stage:
        name: DEV
        identifier: DEV
        blabla: "null"
        delegateSelectors:
          - tag1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hello world"
                          echo "stage.delegateSelectors[0] = <+stage.delegateSelectors[0]>"
                          echo "stage.delegateSelectors[0].delegateSelectors = <+stage.delegateSelectors[0].delegateSelectors>"
                          echo "pipeline.delegateSelectors[1] = <+pipeline.delegateSelectors[1]>"
                          echo "pipeline.delegateSelectors[1].delegateSelectors = <+pipeline.delegateSelectors[1].delegateSelectors>"
                          echo "pipeline.delegateSelectors[0] = <+pipeline.delegateSelectors[0]>"
                          echo "pipeline.delegateSelectors[0].delegateSelectors = <+pipeline.delegateSelectors[0].delegateSelectors>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Abort
