pipeline:  
  name: p1
  identifier: p1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
    orgIdentifier: default  
    tags: {}  
    description:   
    stages:  
        -   
    notificationRules:  
        -   
    flowControl:  
          
    properties:  
          
    timeout:   
    variables:  
        -    
